name: vitamom-backend
region: nyc

services:
  - name: api
    environment_slug: python
    source_dir: /python-free-implementation
    build_command: pip install -r requirements.txt
    run_command: gunicorn production_server:app --bind 0.0.0.0:$PORT --timeout 120
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: PYTHON_VERSION
        value: "3.11.0"
